import './editor.css';
import {siteBounds,clampToSite} from './site.js';

const NS='http://www.w3.org/2000/svg';
export function createEditor({host,getState,onChange,onMode}) {
  const panel=document.createElement('div');panel.className='plan-panel';
  panel.innerHTML=`<svg id="plan" aria-label="Circuit drawing canvas" role="application"><defs><pattern id="smallGrid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="#dce2d5" stroke-width=".15"/></pattern><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><rect width="25" height="25" fill="url(#smallGrid)"/><path d="M25 0H0V25" fill="none" stroke="#becab4" stroke-width=".25"/></pattern></defs><rect class="grid-field" x="-5000" y="-5000" width="10000" height="10000" fill="url(#grid)"/><rect class="site-boundary" x="-105" y="-78" width="210" height="123" fill="none" stroke="#b1bda6" stroke-width=".35" stroke-dasharray="2 2"/><g id="planDrawing"></g></svg><div class="empty-plan"><span>01 / START WITH A POINT</span><h3>A blank canvas.<br>A circuit only you could make.</h3><p>Click anywhere inside the dashed boundary to place your first corner.<br>Keep adding points, then close the loop.</p></div><div class="plan-toolbar"><button data-tool="draw" class="selected">＋ Draw</button><button data-tool="move">↖ Move</button><button data-tool="insert">⊕ Insert</button><button data-tool="delete">− Delete</button><span></span><button id="historyUndo" title="Undo (Ctrl+Z)">↶</button><button id="historyRedo" title="Redo (Ctrl+Shift+Z)">↷</button></div><div class="plan-caption"><span id="planScale">5 m grid</span><span id="planPosition">X 0 · Y 0 m</span></div>`;
  host.append(panel);
  const svg=panel.querySelector('svg'),drawing=panel.querySelector('#planDrawing');
  let tool='draw',mode='2d',selected=-1,drag=null,pan=null,space=false,view=[-140,-105,280,210],history=[],future=[];
  const snapshot=()=>{const s=getState();return {points:s.points.map(p=>[...p]),closed:s.closed};};
  function remember(){history.push(snapshot());if(history.length>80)history.shift();future=[];}
  function commit(s){onChange(s);render();}
  function setTool(t){tool=t;panel.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===t));svg.dataset.tool=t;}
  panel.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
  function undo(){if(!history.length)return;future.push(snapshot());commit(history.pop());}
  function redo(){if(!future.length)return;history.push(snapshot());commit(future.pop());}
  panel.querySelector('#historyUndo').onclick=undo;panel.querySelector('#historyRedo').onclick=redo;
  function screenPoint(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());return [q.x,q.y];}
  const clamp=p=>clampToSite(p,getState().siteScale);
  function applyView(){svg.setAttribute('viewBox',view.join(' '));}
  function zoom(factor,center=[view[0]+view[2]/2,view[1]+view[3]/2]){const w=Math.max(45,Math.min(850*getState().siteScale,view[2]*factor)),f=w/view[2];view=[center[0]+(view[0]-center[0])*f,center[1]+(view[1]-center[1])*f,w,view[3]*f];applyView();}
  function fitSite(){const scale=getState().siteScale||1;view=[-140*scale,-105*scale,280*scale,210*scale];applyView();}
  function fit(){const s=getState();if(!s.points.length)fitSite();else{const ps=s.samples.length?s.samples:s.points.map(p=>({x:p[0],z:p[1]}));const xs=ps.map(p=>p.x),ys=ps.map(p=>p.z),pad=s.width+12;const minX=Math.min(...xs)-pad,maxX=Math.max(...xs)+pad,minY=Math.min(...ys)-pad,maxY=Math.max(...ys)+pad;view=[minX,minY,maxX-minX,maxY-minY];applyView();}}
  function render(){const s=getState(),ps=s.samples,bounds=siteBounds(s.siteScale);const boundary=panel.querySelector('.site-boundary');boundary.setAttribute('x',bounds.minX);boundary.setAttribute('y',bounds.minZ);boundary.setAttribute('width',bounds.maxX-bounds.minX);boundary.setAttribute('height',bounds.maxZ-bounds.minZ);const path=ps.length?ps.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(3)} ${p.z.toFixed(3)}`).join(' ')+(s.closed?' Z':''):'';drawing.replaceChildren();
    function el(tag,attrs){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));drawing.append(n);return n;}
    if(path){el('path',{d:path,fill:'none',stroke:mode==='outline'?'#202d26':'#d2d9c9','stroke-width':s.width+(mode==='outline'?0:2),'stroke-linejoin':'round','stroke-linecap':'round'});if(mode!=='outline'){el('path',{d:path,fill:'none',stroke:'#566452','stroke-width':s.width,'stroke-linejoin':'round','stroke-linecap':'round'});el('path',{d:path,fill:'none',stroke:'#edf1e6','stroke-width':.25,'stroke-dasharray':'2 2'});}}
    if(mode==='2d')s.points.forEach((p,i)=>{el('circle',{cx:p[0],cy:p[1],r:1.65,fill:i===selected?'#2d4533':i===0?'#fff8ed':'#ed7447',stroke:i===0?'#e87547':'#fff','stroke-width':.45,'data-index':i});const label=el('text',{x:p[0]+2.6,y:p[1]-2.6,fill:'#5d7055','font-size':2.8,'font-family':'Arial','pointer-events':'none'});label.textContent=i===0?'START':String(i+1);});
    if(s.closed&&ps.length){const a=ps[Math.round((ps.length-1)*.035)],b=ps[Math.min(ps.length-1,Math.round((ps.length-1)*.035)+1)],dx=b.x-a.x,dy=b.z-a.z,l=Math.hypot(dx,dy)||1;el('line',{x1:a.x-dy/l*s.width/2,y1:a.z+dx/l*s.width/2,x2:a.x+dy/l*s.width/2,y2:a.z-dx/l*s.width/2,stroke:mode==='outline'?'#ed7447':'#fff','stroke-width':.8});}
    panel.querySelector('.empty-plan').classList.toggle('hidden',s.points.length>0);panel.querySelector('#planScale').textContent=mode==='outline'?'START / FINISH marked in orange':'5 m grid';panel.querySelector('#historyUndo').disabled=!history.length;panel.querySelector('#historyRedo').disabled=!future.length;
    document.querySelector('#closeTrack').disabled=s.closed||s.points.length<3;document.querySelector('#clearTrack').disabled=!s.points.length;document.querySelector('#designStatus').textContent=s.closed?'Closed circuit · ready to drive':`${s.points.length} points · ${s.points.length<3?'add at least 3 points':'close the loop when ready'}`;
  }
  svg.addEventListener('pointerdown',e=>{if(e.button===2)return;svg.setPointerCapture(e.pointerId);if(space||e.button===1||mode==='outline'){pan={x:e.clientX,y:e.clientY,view:[...view]};return;}if(mode!=='2d')return;const s=snapshot(),p=clamp(screenPoint(e));const hit=e.target.closest('[data-index]');const index=hit?Number(hit.dataset.index):-1;
    if(index>=0){selected=index;if(tool==='delete'){remember();s.points.splice(index,1);if(s.points.length<3)s.closed=false;commit(s);}else if(tool==='draw'&&index===0&&s.points.length>=3&&!s.closed){remember();s.closed=true;commit(s);setTool('move');}else{remember();drag=index;}render();return;}
    if(tool==='draw'&&!s.closed){if(s.points.some(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<3))return;remember();s.points.push(p);selected=s.points.length-1;commit(s);}else if(tool==='insert'&&s.points.length>=2){let closest=Infinity,at=1;for(let i=0;i<s.points.length-(s.closed?0:1);i++){const a=s.points[i],b=s.points[(i+1)%s.points.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1))),d=Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);if(d<closest){closest=d;at=i+1;}}remember();s.points.splice(at,0,p);selected=at;commit(s);}else if(tool==='move'){pan={x:e.clientX,y:e.clientY,view:[...view]};}
  });
  svg.addEventListener('pointermove',e=>{const p=screenPoint(e);panel.querySelector('#planPosition').textContent=`X ${p[0].toFixed(1)} · Y ${(-p[1]).toFixed(1)} m`;if(pan){const scale=svg.getScreenCTM().a;view=[pan.view[0]-(e.clientX-pan.x)/scale,pan.view[1]-(e.clientY-pan.y)/scale,pan.view[2],pan.view[3]];applyView();}else if(drag!==null){const s=snapshot(),q=clamp(p);if(!s.points.some((v,i)=>i!==drag&&Math.hypot(q[0]-v[0],q[1]-v[1])<3)){s.points[drag]=q;commit(s);}}});
  function end(){drag=null;pan=null;}svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001),screenPoint(e));},{passive:false});
  window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||document.querySelector('dialog[open]')||mode!=='2d')return;if(e.code==='Space'){space=true;e.preventDefault();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}});window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;end();});
  document.querySelector('#closeTrack').onclick=()=>{const s=snapshot();if(s.points.length<3)return;remember();s.closed=true;commit(s);setTool('move');};
  document.querySelector('#clearTrack').onclick=()=>{remember();commit({points:[],closed:false});setTool('draw');fit();onMode('2d');};
  applyView();
  return {render,undo,zoom,fit,fitSite,resetHistory(){history=[];future=[];selected=-1;setTool('draw');},setMode(m){mode=m;panel.classList.toggle('hidden',m==='3d');panel.classList.toggle('outline-mode',m==='outline');render();},export(){const s=getState();if(!s.points.length)return;const clone=svg.cloneNode(true);clone.querySelector('.grid-field').remove();clone.querySelector('.site-boundary').remove();clone.querySelectorAll('circle,text').forEach(n=>n.remove());clone.setAttribute('xmlns',NS);const url=URL.createObjectURL(new Blob([clone.outerHTML],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='circuit.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}};
}
