import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createIcons, PenTool, FolderOpen, Bookmark, Flag, ArrowUpRight, SlidersHorizontal, Settings2, TrafficCone, Trees, Sun, Sunset, Lightbulb, Maximize, Orbit, MousePointer2, Scan, Plus, Minus, RotateCcw, Mouse, Undo2, Route, Ruler, CornerUpRight, Timer, ChartNoAxesColumnIncreasing, X, Square } from 'lucide';
import './style.css';
import './touch.css';
import { createEditor } from './editor.js';
import { createSurroundings } from './surroundings.js';

const icons={PenTool,FolderOpen,Bookmark,Flag,ArrowUpRight,SlidersHorizontal,Settings2,TrafficCone,Trees,Sun,Sunset,Lightbulb,Maximize,Orbit,MousePointer2,Scan,Plus,Minus,RotateCcw,Mouse,Undo2,Route,Ruler,CornerUpRight,Timer,ChartNoAxesColumnIncreasing,X,Square};
const icon = (name, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
document.querySelector('#app').innerHTML = `
<header><a class="brand" href="./"><span class="brand-mark">a<span>↗</span></span>apex<span class="brand-divider"></span><span class="brand-sub">CIRCUIT STUDIO</span></a><nav><button class="nav-active" id="studioNav">${icon('pen-tool')} Design studio</button><button id="circuitsNav">${icon('folder-open')} My circuits <span id="saveCount">0</span></button></nav><div class="header-right"><span class="status-dot"></span> All systems go <span class="avatar">JD</span></div></header>
<main><div class="page-heading"><div><div class="eyebrow">YOUR NEXT GREAT LAP STARTS HERE</div><h1>Make every corner count<span>.</span></h1><p>Dream it. Build it. Drive it. Your circuit, your rules.</p></div><div class="heading-actions"><button class="button secondary" id="save">${icon('bookmark')} Save circuit</button><button class="button primary" id="drive">${icon('flag')} Test drive ${icon('arrow-up-right')}</button></div></div>
<div class="workspace"><aside class="sidebar"><div class="panel-heading"><span>${icon('sliders-horizontal')} Circuit setup</span><span class="small-label">01 — DESIGN</span></div><div class="sidebar-content"><label class="field-label" for="trackName">CIRCUIT NAME</label><input id="trackName" value="Untitled circuit" maxlength="40"/><div class="section-label">BUILD FROM SCRATCH <span>YOUR DESIGN</span></div><p class="build-help">Place your corners in the 2D editor. Click the first point to close your circuit.</p><div class="builder-actions"><button class="button" id="closeTrack">Close loop</button><button class="button" id="clearTrack">New circuit</button></div><p class="design-status" id="designStatus">Start with your first point</p><div class="section-label">TRACK PARAMETERS ${icon('settings-2')}</div><label class="slider-label" for="width">Track width <span><b id="widthValue">8</b> m</span></label><input type="range" id="width" min="5" max="12" step="0.5" value="8"/><div class="range-labels"><span>Tight & technical</span><span>Room to race</span></div><div class="divider"></div><div class="toggle-row"><div>${icon('traffic-cone')}<span>Racing curbs<small>A little room on the limit</small></span></div><button class="toggle on" id="curbs" role="switch" aria-checked="true" aria-label="Racing curbs"></button></div><div class="toggle-row"><div>${icon('trees')}<span>Track surroundings<small>Set the scene</small></span></div><button class="toggle on" id="scenery" role="switch" aria-checked="true" aria-label="Track surroundings"></button></div><select id="biome" aria-label="Surroundings style"><option value="park">Open parkland</option><option value="forest">Pine woodland</option></select><div class="scenery-options"><label><input id="treesOption" type="checkbox" checked/> Trees & rocks</label><label><input id="facilitiesOption" type="checkbox" checked/> Paddock & stands</label><label><input id="barriersOption" type="checkbox" checked/> Safety barriers</label></div><div class="section-label">ATMOSPHERE</div><div class="segmented"><button class="selected" data-light="day">${icon('sun')} Daylight</button><button data-light="golden">${icon('sunset')} Golden hour</button></div><div class="tip"><span>${icon('lightbulb')}</span><div><strong>Great tracks have a rhythm.</strong><p>Scroll to zoom. Hold Space and drag to pan. Use Insert to add a corner and Delete to remove one.</p></div></div></div><div class="sidebar-footer"><span class="status-dot"></span> Built for your imagination.</div></aside>
<section class="viewport" id="viewport"><div id="scene"></div><div class="view-top"><div class="view-badge"><span class="status-dot"></span><span id="modeLabel">LIVE PREVIEW</span><span class="badge-divider"></span><span id="viewLabel">3D perspective</span></div><button class="icon-button" id="fullscreen" title="Toggle fullscreen">${icon('maximize')}</button></div><div class="canvas-title"><span>APEX MOTORSPORT PARK</span><h2 id="canvasName">Untitled circuit</h2><p><span class="orange-dot"></span> PRIVATE CIRCUIT <span>•</span> EST. TODAY</p></div><div class="view-tools"><button class="selected" id="orbit" title="Orbit view">${icon('orbit')}</button><button id="edit" title="Edit track corners">${icon('mouse-pointer-2')}</button><span></span><button id="top" title="Top view">${icon('scan')}</button><button id="zoomIn" title="Zoom in">${icon('plus')}</button><button id="zoomOut" title="Zoom out">${icon('minus')}</button><span></span><button id="reset" title="Reset camera">${icon('rotate-ccw')}</button></div><div class="compass"><span>N</span><div>↑</div></div><div class="drive-hud hidden" id="driveHud"><div class="speed"><strong id="speed">0</strong><span>KM/H</span></div><div class="drive-stat"><small>LAP TIME</small><b id="lapTime">00:00.00</b><small id="lapCount">LAP 01</small></div><button class="button" id="respawn">${icon('rotate-ccw')} Reset kart</button></div><div class="view-bottom"><span id="viewHint">${icon('mouse')} Drag to orbit <span>·</span> Scroll to zoom</span><div class="view-switch"><button id="view2d">2D editor</button><button id="view3d">3D world</button><button id="viewOutline">Circuit only</button><button id="exportSvg" class="hidden">Export SVG</button></div></div><div class="edit-banner hidden" id="editBanner">Drag the orange handles to shape your circuit <button id="undo">${icon('undo-2')} Undo</button></div><div class="track-stamp">DESIGNED TO BE DRIVEN <span>↗</span></div></section></div>
<section class="stats"><div class="stat intro"><span class="stat-icon">${icon('route')}</span><div><small>THE CIRCUIT, AT A GLANCE</small><strong>Your next obsession.</strong></div></div><div class="stat"><span class="stat-icon">${icon('ruler')}</span><div><small>TRACK LENGTH</small><strong><span id="length">0</span> <em>m</em></strong></div></div><div class="stat"><span class="stat-icon">${icon('corner-up-right')}</span><div><small>CORNERS</small><strong id="corners">8</strong></div></div><div class="stat"><span class="stat-icon">${icon('timer')}</span><div><small>EST. LAP TIME</small><strong><span id="estimate">0</span> <em>sec</em></strong></div></div><div class="stat difficulty"><span class="stat-icon">${icon('chart-no-axes-column-increasing')}</span><div><small>DIFFICULTY</small><strong id="difficulty">Intermediate</strong></div><span class="difficulty-bars">▂▄▆<span>█</span></span></div></section>
<footer><span><b>CREATE WITHOUT LIMITS.</b> Chase the perfect lap.</span><span>Made for the love of karting <span class="footer-cross">✳</span></span></footer></main><div class="toast" id="toast"></div><dialog id="savedDialog"><div class="modal-heading"><div><div class="eyebrow">YOUR PERSONAL PADDOCK</div><h2>My circuits</h2></div><button id="closeDialog" class="icon-button" aria-label="Close">${icon('x')}</button></div><div id="savedList"></div></dialog>`;
createIcons({icons});

let points=[],closed=false,width=8,showCurbs=true,showScenery=true,editing=false,driving=false,overhead=false,undoStack=[],viewMode='2d',editor=null;
let environment={trees:true,facilities:true,barriers:true,biome:'park'};
let saved=[];try {saved=JSON.parse(localStorage.getItem('apex-circuits')||'[]');if(!Array.isArray(saved))saved=[];}catch{};
document.querySelector('#saveCount').textContent=saved.length;
const scene=new THREE.Scene();scene.background=new THREE.Color('#c6ceba');scene.fog=new THREE.Fog('#c6ceba',230,650);
const container=document.querySelector('#scene');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#c6ceba');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,1,1,700);camera.position.set(133,145,166);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,-2);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2.12;controls.minDistance=45;controls.maxDistance=340;
const ambient=new THREE.HemisphereLight('#e5f0ff','#626e49',2.5);scene.add(ambient);const sun=new THREE.DirectionalLight('#fff5dd',3.2);sun.position.set(-70,110,65);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-140,right:140,top:130,bottom:-130,near:1,far:350});sun.shadow.bias=-.0006;scene.add(sun);
const mat=(color,options={})=>new THREE.MeshStandardMaterial({color,roughness:.9,...options});
const grass=mat('#80936a'), asphalt=mat('#383e3c'), white=mat('#f2ece0'), red=mat('#d3573e'), dark=mat('#262e2a'), orange=mat('#f06936'), concrete=mat('#b6b7a5');
function mesh(geo,material,parent=scene){const m=new THREE.Mesh(geo,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,x,y,z,material,parent=scene){const m=mesh(new THREE.BoxGeometry(w,h,d),material,parent);m.position.set(x,y,z);return m;}
box(255,2.5,205,0,-1.5,0,grass);const floor=mesh(new THREE.PlaneGeometry(2000,2000),mat('#bac3ac'));floor.rotation.x=-Math.PI/2;floor.position.y=-2.8;
// Fine asphalt grain is generated locally, so the studio works without image services.
const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=128;const tc=textureCanvas.getContext('2d');tc.fillStyle='#686b66';tc.fillRect(0,0,128,128);let seed=13;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}for(let i=0;i<6000;i++){let c=70+random()*95;tc.fillStyle=`rgb(${c},${c},${c})`;tc.fillRect(random()*128,random()*128,1,1);}const roadTexture=new THREE.CanvasTexture(textureCanvas);roadTexture.wrapS=roadTexture.wrapT=THREE.RepeatWrapping;roadTexture.repeat.set(16,4);asphalt.map=roadTexture;
let trackGroup=new THREE.Group(),handleGroup=new THREE.Group(),scenery=new THREE.Group();scene.add(trackGroup,handleGroup,scenery);let curve,samples=[],totalLength=0;
function disposeGroup(g){while(g.children.length){const c=g.children[0];g.remove(c);c.traverse(o=>{if(o.geometry)o.geometry.dispose();});}}
function ribbon(inner,outer,y,material){const verts=[],uv=[],inds=[];const count=480;for(let i=0;i<=count;i++){const t=i/count,p=curve.getPointAt(t),tan=curve.getTangentAt(t),normal=new THREE.Vector3(-tan.z,0,tan.x);for(const offset of [inner,outer]){const v=p.clone().addScaledVector(normal,offset);verts.push(v.x,y,v.z);uv.push(t,offset===inner?0:1);}if(i<count){const j=i*2;inds.push(j,j+1,j+2,j+1,j+3,j+2);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(inds);g.computeVertexNormals();mesh(g,material,trackGroup).castShadow=false;}
function buildTrack(){disposeGroup(trackGroup);disposeGroup(handleGroup);
 document.querySelector('#drive').disabled=!closed||points.length<3;
 if(points.length<2){curve=null;samples=[];totalLength=0;document.querySelector('#length').textContent='0';document.querySelector('#corners').textContent=points.length;document.querySelector('#estimate').textContent='—';document.querySelector('#difficulty').textContent='Draft';return;}
 curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],0,p[1])),closed,'catmullrom',.38);totalLength=curve.getLength();samples=curve.getSpacedPoints(600);ribbon(-width/2-1.8,width/2+1.8,.01,concrete);ribbon(-width/2,width/2,.04,asphalt);ribbon(-width/2+.23,-width/2+.38,.061,white);ribbon(width/2-.38,width/2-.23,.061,white);
 if(showCurbs){const count=Math.floor(totalLength/2);for(let i=0;i<count;i++){const t=i/count,p=curve.getPointAt(t),tan=curve.getTangentAt(t),n=new THREE.Vector3(-tan.z,0,tan.x);for(const side of [-1,1]){const curb=box(.8,.13,totalLength/count+.05,p.x+n.x*(width/2+.42)*side,.12,p.z+n.z*(width/2+.42)*side,i%2?white:red,trackGroup);curb.rotation.y=Math.atan2(tan.x,tan.z);}}}
 const p=curve.getPointAt(.035),tan=curve.getTangentAt(.035);const start=new THREE.Group();start.position.copy(p);start.rotation.y=Math.atan2(tan.x,tan.z);trackGroup.add(start);for(let x=0;x<Math.floor(width/.65);x++)for(let z=0;z<3;z++)box(.65,.025,.65,-width/2+.325+x*.65,.075,(z-1)*.65,(x+z)%2?white:dark,start);
 points.forEach((p,i)=>{const h=mesh(new THREE.SphereGeometry(1.55,16,12),orange,handleGroup);h.position.set(p[0],1.65,p[1]);h.userData.index=i;});handleGroup.visible=editing;
 document.querySelector('#length').textContent=Math.round(totalLength);document.querySelector('#corners').textContent=points.length;document.querySelector('#estimate').textContent=Math.round(totalLength/13);document.querySelector('#difficulty').textContent=closed?'Custom circuit':'Draft';}
buildTrack();
const rebuildSurroundings=createSurroundings(scenery);
function updateSurroundings(){rebuildSurroundings({samples,width,...environment});scenery.visible=showScenery;}
updateSurroundings();
const kart=new THREE.Group();scene.add(kart);box(2,.4,3.2,0,.65,0,dark,kart);box(1.55,.5,1.3,0,.95,.9,orange,kart);box(1.8,.35,.3,0,.5,1.8,orange,kart);box(.85,.7,.7,0,1.1,-.35,dark,kart);const helmet=mesh(new THREE.SphereGeometry(.43,16,12),white,kart);helmet.position.set(0,1.95,-.3);box(.65,.17,.12,0,1.98,.09,dark,kart);for(const x of [-1.05,1.05])for(const z of [-1.1,1.1]){const wheel=mesh(new THREE.CylinderGeometry(.43,.43,.4,12),dark,kart);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.43,z);}
let velocity=0,heading=0,lapStart=0,laps=0,progress=0,lastProgress=.035,lapArmed=false,bestLap=null;const keys=new Set();
function resetKart(){kart.visible=closed&&points.length>=3;if(!curve)return;bestLap=null;const p=curve.getPointAt(.035),t=curve.getTangentAt(.035);kart.position.copy(p);heading=Math.atan2(t.x,t.z);kart.rotation.y=heading;velocity=0;lapStart=performance.now();lastProgress=.035;progress=0;lapArmed=false;}
resetKart();
const $=s=>document.querySelector(s);function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function setEdit(value){editing=value;handleGroup.visible=value;$('#edit').classList.toggle('selected',value);$('#orbit').classList.toggle('selected',!value);$('#editBanner').classList.toggle('hidden',!value);}
function cameraView(top=false){setView(top?'2d':'3d');}
function setView(mode){if(driving)return;viewMode=mode;overhead=mode!=='3d';controls.enabled=mode==='3d';container.style.visibility=mode==='3d'?'visible':'hidden';$('#viewport').classList.toggle('plan-active',mode!=='3d');$('#viewLabel').textContent=mode==='3d'?'3D perspective':mode==='2d'?'Scale drawing':'Circuit silhouette';$('#viewHint').textContent=mode==='3d'?'Drag to orbit · Scroll to zoom':mode==='2d'?'Click to draw · Scroll to zoom · Space + drag to pan':'Circuit only · Scroll to zoom · Drag to pan';$('#modeLabel').textContent=mode==='2d'?'DESIGN CANVAS':mode==='outline'?'CIRCUIT PLAN':'LIVE PREVIEW';for(const [id,m] of [['#view2d','2d'],['#view3d','3d'],['#viewOutline','outline']])$(id).classList.toggle('selected',mode===m);$('#exportSvg').classList.toggle('hidden',mode!=='outline');setEdit(false);editor?.setMode(mode);if(mode==='3d'){controls.target.set(0,0,-2);camera.position.set(133,145,166);updateSurroundings();}else if(mode==='outline')editor?.fit();}
editor=createEditor({host:$('#viewport'),getState:()=>({points,closed,width,samples}),onChange:s=>{points=s.points;closed=s.closed;buildTrack();resetKart();},onMode:setView});
$('#edit').onclick=()=>setView('2d');$('#orbit').onclick=()=>setView('3d');$('#top').onclick=()=>setView('2d');$('#view2d').onclick=()=>setView('2d');$('#view3d').onclick=()=>setView('3d');$('#viewOutline').onclick=()=>setView('outline');$('#exportSvg').onclick=()=>editor.export();$('#reset').onclick=()=>{if(viewMode==='3d')setView('3d');else editor.fit();};$('#zoomIn').onclick=()=>{if(viewMode==='3d')camera.position.lerp(controls.target,.15);else editor.zoom(.8);};$('#zoomOut').onclick=()=>{if(viewMode==='3d')camera.position.sub(controls.target).multiplyScalar(1.15).add(controls.target);else editor.zoom(1.25);};
setView('2d');
for(const [id,key] of [['#treesOption','trees'],['#facilitiesOption','facilities'],['#barriersOption','barriers']])$(id).onchange=e=>{environment[key]=e.target.checked;updateSurroundings();};$('#biome').onchange=e=>{environment.biome=e.target.value;updateSurroundings();};
$('#width').oninput=e=>{width=+e.target.value;$('#widthValue').textContent=width;buildTrack();editor.render();updateSurroundings();};
$('#curbs').onclick=()=>{showCurbs=!showCurbs;$('#curbs').classList.toggle('on',showCurbs);$('#curbs').setAttribute('aria-checked',showCurbs);buildTrack();};$('#scenery').onclick=()=>{showScenery=!showScenery;scenery.visible=showScenery;$('#scenery').classList.toggle('on',showScenery);$('#scenery').setAttribute('aria-checked',showScenery);};
document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{const golden=b.dataset.light==='golden';sun.color.set(golden?'#ffc17b':'#fff5dd');sun.position.set(-70,golden?35:110,65);ambient.intensity=golden?1.8:2.5;scene.background.set(golden?'#d6bea0':'#c6ceba');scene.fog.color.copy(scene.background);document.querySelectorAll('[data-light]').forEach(v=>v.classList.toggle('selected',v===b));});
$('#trackName').oninput=e=>{$('#canvasName').textContent=e.target.value.trim()||'Untitled circuit';};
$('#undo').onclick=()=>editor.undo();
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
function driveToggle(){if(!driving){if(!closed||points.length<3)return;setView('3d');}driving=!driving;setEdit(false);controls.enabled=!driving;$('#drive').innerHTML=driving?`${icon('square')} End test drive`:`${icon('flag')} Test drive ${icon('arrow-up-right')}`;$('#modeLabel').textContent=driving?'ON THE CIRCUIT':'LIVE PREVIEW';$('#driveHud').classList.toggle('hidden',!driving);$('#viewHint').innerHTML=driving?'W / ↑ Accelerate <span>·</span> S / ↓ Brake & reverse <span>·</span> A D Steer <span>·</span> R Reset':`${icon('mouse')} Drag to orbit <span>·</span> Scroll to zoom`;$('.canvas-title').classList.toggle('hidden',driving);$('.view-tools').classList.toggle('hidden',driving);$('.view-switch').classList.toggle('hidden',driving);$('#width').disabled=driving;$('.sidebar').inert=driving;keys.clear();if(driving){resetKart();laps=0;$('#lapCount').textContent='LAP 01';toast('You’re in the driver’s seat. Use WASD or arrow keys.');}else cameraView(false);createIcons({icons});}
$('#drive').onclick=driveToggle;$('#respawn').onclick=resetKart;
const touchControls=document.createElement('div');touchControls.className='touch-controls';touchControls.innerHTML='<div><button data-key="a" aria-label="Steer left">←</button><button data-key="d" aria-label="Steer right">→</button></div><div><button data-key="s" aria-label="Brake and reverse">BRAKE</button><button data-key="w" aria-label="Accelerate">GO ↑</button></div>';$('#viewport').append(touchControls);
new MutationObserver(()=>touchControls.classList.toggle('visible',driving)).observe($('#driveHud'),{attributes:true,attributeFilter:['class']});
touchControls.querySelectorAll('button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
window.addEventListener('keydown',e=>{if(e.target.matches('input')||$('#savedDialog').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(driving&&e.key.toLowerCase()==='r')resetKart();if(driving&&e.key==='Escape')driveToggle();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let dragged=null;
function pointerRay(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);}
renderer.domElement.addEventListener('pointerdown',e=>{if(!editing)return;pointerRay(e);const hit=raycaster.intersectObjects(handleGroup.children);if(hit.length){dragged=hit[0].object.userData.index;undoStack.push(points.map(p=>[...p]));controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);}},true);
renderer.domElement.addEventListener('pointermove',e=>{if(dragged===null)return;pointerRay(e);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){points[dragged]=[THREE.MathUtils.clamp(p.x,-105,105),THREE.MathUtils.clamp(p.z,-78,45)];buildTrack();}});
renderer.domElement.addEventListener('pointerup',()=>{if(dragged!==null){dragged=null;controls.enabled=true;resetKart();}});
$('#save').onclick=()=>{if(!points.length){toast('Place a point before saving your circuit.');return;}const data={id:Date.now(),name:$('#trackName').value.trim()||'Untitled circuit',points:points.map(p=>[...p]),closed,width,showCurbs,showScenery,environment:{...environment}};const existing=saved.findIndex(s=>s.name===data.name);if(existing>=0)saved[existing]=data;else saved.push(data);try{localStorage.setItem('apex-circuits',JSON.stringify(saved));$('#saveCount').textContent=saved.length;toast('Circuit saved. Your next lap is waiting.');}catch{toast('Storage is full or unavailable. Unable to save circuit.');}};
function showSaved(){$('#savedList').replaceChildren();if(!saved.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Your garage is empty. Design a circuit and save it to find it here.';$('#savedList').append(p);}saved.forEach(s=>{const b=document.createElement('button');b.className='saved-item';const title=document.createElement('strong');title.textContent=s.name;const detail=document.createElement('span');detail.textContent=`${s.points.length} corners · ${s.width} m wide →`;b.append(title,detail);b.onclick=()=>{if(driving)driveToggle();points=s.points.map(p=>[...p]);width=s.width;closed=s.closed??true;showCurbs=s.showCurbs;showScenery=s.showScenery??true;environment={trees:true,facilities:true,barriers:true,biome:'park',...s.environment};$('#scenery').classList.toggle('on',showScenery);$('#scenery').setAttribute('aria-checked',showScenery);for(const [id,key] of [['#treesOption','trees'],['#facilitiesOption','facilities'],['#barriersOption','barriers']])$(id).checked=environment[key];$('#biome').value=environment.biome;$('#curbs').classList.toggle('on',showCurbs);$('#curbs').setAttribute('aria-checked',showCurbs);$('#trackName').value=s.name;$('#canvasName').textContent=s.name;$('#width').value=width;$('#widthValue').textContent=width;undoStack=[];editor.resetHistory();buildTrack();resetKart();updateSurroundings();setView('2d');editor.fit();$('#savedDialog').close();toast('Circuit loaded. Make it yours.');};$('#savedList').append(b);});$('#savedDialog').showModal();}
$('#circuitsNav').onclick=showSaved;$('#closeDialog').onclick=()=>$('#savedDialog').close();$('#studioNav').onclick=()=>$('#savedDialog').close();
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);resize();
let previous=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-previous)/1000,.045);previous=now;if(driving){let nearest=Infinity,idx=0;for(let i=0;i<samples.length;i++){const d=kart.position.distanceToSquared(samples[i]);if(d<nearest){nearest=d;idx=i;}}const onRoad=Math.sqrt(nearest)<width/2;const throttle=keys.has('w')||keys.has('arrowup'),brake=keys.has('s')||keys.has('arrowdown');velocity+=(throttle?12:0)*dt;velocity-=(brake?(velocity>0?22:7):0)*dt;velocity*=Math.exp(-(onRoad?.22:1.9)*dt);velocity=THREE.MathUtils.clamp(velocity,-7,onRoad?29:10);if(!throttle&&!brake&&Math.abs(velocity)<.15)velocity=0;const steer=(keys.has('a')||keys.has('arrowleft')?1:0)-(keys.has('d')||keys.has('arrowright')?1:0);heading+=steer*dt*1.6*Math.min(Math.abs(velocity)/9,1)*Math.sign(velocity);kart.position.x+=Math.sin(heading)*velocity*dt;kart.position.z+=Math.cos(heading)*velocity*dt;kart.position.x=THREE.MathUtils.clamp(kart.position.x,-122,122);kart.position.z=THREE.MathUtils.clamp(kart.position.z,-97,97);kart.rotation.y=heading;
 const t=idx/600;let delta=t-lastProgress;if(delta>.5)delta-=1;if(delta<-.5)delta+=1;if(onRoad&&Math.abs(delta)<.06)progress+=delta;lastProgress=t;if(progress>.85)lapArmed=true;if(lapArmed&&progress>=1&&onRoad){const time=(now-lapStart)/1000;bestLap=bestLap?Math.min(time,bestLap):time;laps++;lapStart=now;progress=0;lapArmed=false;$('#lapCount').textContent=`LAP ${String(laps+1).padStart(2,'0')}`;toast(`Lap complete · ${time.toFixed(2)}s — Best ${bestLap.toFixed(2)}s`);}const seconds=(now-lapStart)/1000;$('#lapTime').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${(seconds%60).toFixed(2).padStart(5,'0')}`;$('#speed').textContent=Math.round(Math.abs(velocity)*3.6);
 const target=kart.position.clone().add(new THREE.Vector3(-Math.sin(heading)*13,9,-Math.cos(heading)*13));camera.position.lerp(target,1-Math.exp(-5*dt));camera.lookAt(kart.position.clone().add(new THREE.Vector3(Math.sin(heading)*7,1,Math.cos(heading)*7)));}else if(viewMode==='3d')controls.update();if(driving||viewMode==='3d')renderer.render(scene,camera);}requestAnimationFrame(frame);
