import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createIcons, PenTool, FolderOpen, Bookmark, Flag, ArrowUpRight, SlidersHorizontal, Settings2, TrafficCone, Trees, Sun, Sunset, Lightbulb, Maximize, Orbit, MousePointer2, Scan, Plus, Minus, RotateCcw, Mouse, Undo2, Route, Ruler, CornerUpRight, Timer, ChartNoAxesColumnIncreasing, X, Square, Trash2 } from 'lucide';
import './style.css';
import './touch.css';
import './refinement.css';
import { createEditor } from './editor.js';
import { createSurroundings } from './surroundings.js';
import { buildTrackGeometry } from './track-geometry.js';
import { makeCurbTexture } from './curb-paint.js';
import {siteBounds,pointInsideSite,clampToSite} from './site.js';
import {stepKart} from './kart-physics.js';
import {createKart} from './kart.js';

const icons={PenTool,FolderOpen,Bookmark,Flag,ArrowUpRight,SlidersHorizontal,Settings2,TrafficCone,Trees,Sun,Sunset,Lightbulb,Maximize,Orbit,MousePointer2,Scan,Plus,Minus,RotateCcw,Mouse,Undo2,Route,Ruler,CornerUpRight,Timer,ChartNoAxesColumnIncreasing,X,Square,Trash2};
const icon = (name, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
document.querySelector('#app').innerHTML = `
<header><a class="brand" href="./"><span class="brand-mark">a<span>↗</span></span>apex<span class="brand-divider"></span><span class="brand-sub">CIRCUIT STUDIO</span></a><nav><button class="nav-active" id="studioNav">${icon('pen-tool')} Design studio</button><button id="circuitsNav">${icon('folder-open')} My circuits <span id="saveCount">0</span></button></nav><div class="header-right"><span class="status-dot"></span> All systems go <span class="avatar">JD</span></div></header>
<main><div class="page-heading"><div><div class="eyebrow">YOUR NEXT GREAT LAP STARTS HERE</div><h1>Make every corner count<span>.</span></h1><p>Dream it. Build it. Drive it. Your circuit, your rules.</p></div><div class="heading-actions"><button class="button secondary" id="save">${icon('bookmark')} Save circuit</button><button class="button primary" id="drive">${icon('flag')} Test drive ${icon('arrow-up-right')}</button></div></div>
<div class="workspace"><aside class="sidebar"><div class="panel-heading"><span>${icon('sliders-horizontal')} Circuit setup</span><span class="small-label">01 — DESIGN</span></div><div class="sidebar-content"><label class="field-label" for="trackName">CIRCUIT NAME</label><input id="trackName" value="Untitled circuit" maxlength="40"/><div class="section-label">BUILD FROM SCRATCH <span>YOUR DESIGN</span></div><p class="build-help">Place your corners in the 2D editor. Click the first point to close your circuit.</p><div class="builder-actions"><button class="button" id="closeTrack">Close loop</button><button class="button" id="clearTrack">New circuit</button></div><p class="design-status" id="designStatus">Start with your first point</p><div class="section-label">TRACK PARAMETERS ${icon('settings-2')}</div><label class="slider-label" for="width">Track width <span><b id="widthValue">8</b> m</span></label><input type="range" id="width" min="5" max="12" step="0.5" value="8"/><div class="range-labels"><span>Tight & technical</span><span>Room to race</span></div><div class="divider"></div><div class="toggle-row"><div>${icon('traffic-cone')}<span>Racing curbs<small>A little room on the limit</small></span></div><button class="toggle on" id="curbs" role="switch" aria-checked="true" aria-label="Racing curbs"></button></div><div class="toggle-row"><div>${icon('trees')}<span>Track surroundings<small>Set the scene</small></span></div><button class="toggle on" id="scenery" role="switch" aria-checked="true" aria-label="Track surroundings"></button></div><select id="biome" aria-label="Surroundings style"><option value="park">Open parkland</option><option value="forest">Pine woodland</option></select><div class="scenery-options"><label><input id="treesOption" type="checkbox" checked/> Trees & rocks</label><label><input id="facilitiesOption" type="checkbox" checked/> Paddock & stands</label><label><input id="barriersOption" type="checkbox" checked/> Safety barriers</label></div><div class="section-label">ATMOSPHERE</div><div class="segmented"><button class="selected" data-light="day">${icon('sun')} Daylight</button><button data-light="golden">${icon('sunset')} Golden hour</button></div><div class="tip"><span>${icon('lightbulb')}</span><div><strong>Great tracks have a rhythm.</strong><p>Scroll to zoom. Hold Space and drag to pan. Use Insert to add a corner and Delete to remove one.</p></div></div></div><div class="sidebar-footer"><span class="status-dot"></span> Built for your imagination.</div></aside>
<section class="viewport" id="viewport"><div id="scene"></div><div class="view-top"><div class="view-badge"><span class="status-dot"></span><span id="modeLabel">LIVE PREVIEW</span><span class="badge-divider"></span><span id="viewLabel">3D perspective</span></div><button class="icon-button" id="fullscreen" title="Toggle fullscreen">${icon('maximize')}</button></div><div class="canvas-title"><span>APEX MOTORSPORT PARK</span><h2 id="canvasName">Untitled circuit</h2><p><span class="orange-dot"></span> PRIVATE CIRCUIT <span>•</span> EST. TODAY</p></div><div class="view-tools"><button class="selected" id="orbit" title="Orbit view">${icon('orbit')}</button><button id="edit" title="Edit track corners">${icon('mouse-pointer-2')}</button><span></span><button id="top" title="Top view">${icon('scan')}</button><button id="zoomIn" title="Zoom in">${icon('plus')}</button><button id="zoomOut" title="Zoom out">${icon('minus')}</button><span></span><button id="reset" title="Reset camera">${icon('rotate-ccw')}</button></div><div class="compass"><span>N</span><div>↑</div></div><div class="drive-hud hidden" id="driveHud"><div class="speed"><strong id="speed">0</strong><span>KM/H</span></div><div class="drive-stat"><small>LAP TIME</small><b id="lapTime">00:00.00</b><small id="lapCount">LAP 01</small></div><button class="button" id="respawn">${icon('rotate-ccw')} Reset kart</button></div><div class="view-bottom"><span id="viewHint">${icon('mouse')} Drag to orbit <span>·</span> Scroll to zoom</span><div class="view-switch"><button id="view2d">2D editor</button><button id="view3d">3D world</button><button id="viewOutline">Circuit only</button><button id="exportSvg" class="hidden">Export SVG</button></div></div><div class="edit-banner hidden" id="editBanner">Drag the orange handles to shape your circuit <button id="undo">${icon('undo-2')} Undo</button></div><div class="track-stamp">DESIGNED TO BE DRIVEN <span>↗</span></div></section></div>
<section class="stats"><div class="stat intro"><span class="stat-icon">${icon('route')}</span><div><small>THE CIRCUIT, AT A GLANCE</small><strong>Your next obsession.</strong></div></div><div class="stat"><span class="stat-icon">${icon('ruler')}</span><div><small>TRACK LENGTH</small><strong><span id="length">0</span> <em>m</em></strong></div></div><div class="stat"><span class="stat-icon">${icon('corner-up-right')}</span><div><small>CORNERS</small><strong id="corners">8</strong></div></div><div class="stat"><span class="stat-icon">${icon('timer')}</span><div><small>EST. LAP TIME</small><strong><span id="estimate">0</span> <em>sec</em></strong></div></div><div class="stat difficulty"><span class="stat-icon">${icon('chart-no-axes-column-increasing')}</span><div><small>DIFFICULTY</small><strong id="difficulty">Intermediate</strong></div><span class="difficulty-bars">▂▄▆<span>█</span></span></div></section>
<footer><span><b>CREATE WITHOUT LIMITS.</b> Chase the perfect lap.</span><span>Made for the love of karting <span class="footer-cross">✳</span></span></footer></main><div class="toast" id="toast"></div><dialog id="savedDialog"><div class="modal-heading"><div><div class="eyebrow">YOUR PERSONAL PADDOCK</div><h2>My circuits</h2></div><button id="closeDialog" class="icon-button" aria-label="Close">${icon('x')}</button></div><div id="savedList"></div></dialog>`;
createIcons({icons});
document.querySelector('.range-labels').insertAdjacentHTML('afterend', '<label class="slider-label smoothness-label" for="smoothness">Corner flow <span id="smoothnessValue">Balanced</span></label><input type="range" id="smoothness" min="0.1" max="0.8" step="0.05" value="0.4"/><div class="range-labels"><span>Precise</span><span>Flowing</span></div>');
document.querySelector('#smoothness').nextElementSibling.insertAdjacentHTML('afterend', '<label class="slider-label smoothness-label" for="curbWidth">Curb width <span><b id="curbWidthValue">0.9</b> m</span></label><input type="range" id="curbWidth" min="0.5" max="1.5" step="0.1" value="0.9"/><label class="slider-label smoothness-label" for="runoffWidth">Runoff width <span><b id="runoffWidthValue">1.1</b> m</span></label><input type="range" id="runoffWidth" min="0.5" max="3" step="0.1" value="1.1"/><label class="slider-label smoothness-label" for="miterLimit">Corner join limit <span><b id="miterLimitValue">2</b>×</span></label><input type="range" id="miterLimit" min="1.2" max="3" step="0.1" value="2"/><label class="geometry-debug-label"><input type="checkbox" id="geometryDebug"/> Show geometry guides</label>');
document.querySelector('#biome').insertAdjacentHTML('afterend', '<label class="slider-label smoothness-label" for="sceneryDensity">Landscape density <span id="sceneryDensityValue">Medium</span></label><input type="range" id="sceneryDensity" min="50" max="180" step="10" value="100"/><div class="range-labels"><span>Open</span><span>Lush</span></div>');
document.querySelector('.builder-actions').insertAdjacentHTML('afterend','<label class="field-label site-size-label" for="siteScale">CIRCUIT AREA</label><select id="siteScale" aria-label="Circuit area"><option value="1">Standard · 210 × 123 m</option><option value="2">Large · 420 × 246 m</option><option value="3">Grand · 630 × 369 m</option></select><p class="site-size-hint">Expand the site to draw longer straights and bigger layouts.</p>');
document.querySelector('#viewport').insertAdjacentHTML('beforeend', '<div id="geometryLegend" class="geometry-legend hidden"><strong>GEOMETRY GUIDES</strong><span><i style="background:#ff9f36"></i> Centerline</span><span><i style="background:#7bedb2"></i> Left boundary</span><span><i style="background:#4db9ff"></i> Right boundary</span><span><i style="background:#bc77ff"></i> Curb inner edge</span><span><i style="background:#fc668d"></i> Curb outer edge</span><span><i style="background:#ff2fa9"></i> Repaired intersection</span><small id="geometryStatus">No intersections found</small></div>');

let points=[],closed=false,width=8,smoothness=.4,curbWidth=.9,runoffWidth=1.1,miterLimit=2,siteScale=1,geometryDebug=false,showCurbs=true,showScenery=true,editing=false,driving=false,overhead=false,undoStack=[],viewMode='2d',editor=null;
let environment={trees:true,facilities:true,barriers:true,biome:'park',density:100};
let saved=[];try {saved=JSON.parse(localStorage.getItem('apex-circuits')||'[]');if(!Array.isArray(saved))saved=[];}catch{};
document.querySelector('#saveCount').textContent=saved.length;
const scene=new THREE.Scene();scene.background=new THREE.Color('#c6ceba');scene.fog=new THREE.Fog('#c6ceba',230,650);
const container=document.querySelector('#scene');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#c6ceba');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,1,1,2400);camera.position.set(133,145,166);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,-2);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2.12;controls.minDistance=20;controls.maxDistance=1000;
const ambient=new THREE.HemisphereLight('#e5f0ff','#626e49',2.5);scene.add(ambient);const sun=new THREE.DirectionalLight('#fff5dd',3.2);sun.position.set(-70,110,65);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-140,right:140,top:130,bottom:-130,near:1,far:350});sun.shadow.bias=-.0006;scene.add(sun);
const mat=(color,options={})=>new THREE.MeshStandardMaterial({color,roughness:.9,...options});
const grass=mat('#80936a'), asphalt=mat('#383e3c'), white=mat('#f2ece0'), red=mat('#d3573e'), dark=mat('#262e2a'), orange=mat('#f06936'), concrete=mat('#b6b7a5'), curbMaterial=new THREE.MeshStandardMaterial({roughness:.92});
function mesh(geo,material,parent=scene){const m=new THREE.Mesh(geo,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,x,y,z,material,parent=scene){const m=mesh(new THREE.BoxGeometry(w,h,d),material,parent);m.position.set(x,y,z);return m;}
const siteGround=box(255,2.5,205,0,-1.5,0,grass);const floor=mesh(new THREE.PlaneGeometry(2400,2400),mat('#bac3ac'));floor.rotation.x=-Math.PI/2;floor.position.y=-2.8;
function updateSite(){siteGround.scale.set(siteScale,1,siteScale);sun.shadow.camera.left=-140*siteScale;sun.shadow.camera.right=140*siteScale;sun.shadow.camera.top=130*siteScale;sun.shadow.camera.bottom=-130*siteScale;sun.shadow.camera.updateProjectionMatrix();scene.fog.near=230*siteScale;scene.fog.far=650*siteScale;}
updateSite();
// Fine asphalt grain is generated locally, so the studio works without image services.
const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=128;const tc=textureCanvas.getContext('2d');tc.fillStyle='#686b66';tc.fillRect(0,0,128,128);let seed=13;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}for(let i=0;i<6000;i++){let c=70+random()*95;tc.fillStyle=`rgb(${c},${c},${c})`;tc.fillRect(random()*128,random()*128,1,1);}const roadTexture=new THREE.CanvasTexture(textureCanvas);roadTexture.wrapS=roadTexture.wrapT=THREE.RepeatWrapping;roadTexture.repeat.set(1,1);asphalt.map=roadTexture;
let trackGroup=new THREE.Group(),handleGroup=new THREE.Group(),scenery=new THREE.Group(),debugGroup=new THREE.Group(),trackModel=null;scene.add(trackGroup,handleGroup,scenery,debugGroup);let curve,samples=[],totalLength=0;
function disposeGroup(g,disposeMaterials=false){while(g.children.length){const c=g.children[0];g.remove(c);c.traverse(o=>{if(o.geometry)o.geometry.dispose();if(disposeMaterials&&o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}}
function drawGuide(path,color,y,closed=true){if(path.length<2)return;const vertices=path.map(p=>new THREE.Vector3(p.x,y,p.z));if(closed)vertices.push(vertices[0]);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(vertices),new THREE.LineBasicMaterial({color,depthTest:false}));line.renderOrder=20;debugGroup.add(line);}
function buildTrack(){disposeGroup(trackGroup);disposeGroup(handleGroup);disposeGroup(debugGroup,true);curbMaterial.map?.dispose();curbMaterial.map=null;curbMaterial.needsUpdate=true;
 document.querySelector('#drive').disabled=!closed||points.length<3;
 if(points.length<2){curve=null;trackModel=null;samples=[];totalLength=0;document.querySelector('#length').textContent='0';document.querySelector('#corners').textContent=points.length;document.querySelector('#estimate').textContent='—';document.querySelector('#difficulty').textContent='Draft';return;}
 curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],0,p[1])),closed,'catmullrom',smoothness);totalLength=curve.getLength();samples=curve.getSpacedPoints(Math.max(600,Math.ceil(totalLength/1.2)));
 trackModel=buildTrackGeometry(curve,{closed,width,curbWidth,runoffWidth,miterLimit,debug:geometryDebug});
 if(trackModel){if(showCurbs){curbMaterial.map=makeCurbTexture(trackModel.centerline,width,curbWidth,closed);curbMaterial.needsUpdate=true;}for(const [geometry,material] of [[trackModel.shoulder,concrete],[trackModel.road,asphalt],[trackModel.white,white],...(showCurbs?[[trackModel.curb,curbMaterial]]:[])]){const surface=mesh(geometry,material,trackGroup);surface.castShadow=false;surface.receiveShadow=false;}if(!showCurbs)trackModel.curb.dispose();}
 if(geometryDebug&&trackModel){drawGuide(trackModel.centerline,'#ff9f36',.2,closed);drawGuide(trackModel.leftBoundary,'#7bedb2',.26,closed);drawGuide(trackModel.rightBoundary,'#4db9ff',.26,closed);for(const boundary of trackModel.boundaries){drawGuide(boundary.outer,'#bc77ff',.22);boundary.holes.forEach(h=>drawGuide(h,'#bc77ff',.22));}for(const edge of trackModel.curbEdges){drawGuide(edge.outer,'#fc668d',.24);edge.holes.forEach(h=>drawGuide(h,'#fc668d',.24));}for(const p of trackModel.intersectionPoints){const marker=mesh(new THREE.SphereGeometry(.65,10,8),mat('#ff2fa9'),debugGroup);marker.position.set(p.x,.5,p.z);}document.querySelector('#geometryStatus').textContent=trackModel.intersectionPoints.length?`${trackModel.intersectionPoints.length} offset crossing${trackModel.intersectionPoints.length===1?'':'s'} repaired`:'No offset crossings detected';}
 if(closed){const p=curve.getPointAt(.035),tan=curve.getTangentAt(.035);const start=new THREE.Group();start.position.copy(p);start.rotation.y=Math.atan2(tan.x,tan.z);trackGroup.add(start);for(let x=0;x<Math.floor(width/.65);x++)for(let z=0;z<3;z++)box(.65,.025,.65,-width/2+.325+x*.65,.075,(z-1)*.65,(x+z)%2?white:dark,start);}
 points.forEach((p,i)=>{const h=mesh(new THREE.SphereGeometry(1.55,16,12),orange,handleGroup);h.position.set(p[0],1.65,p[1]);h.userData.index=i;});handleGroup.visible=editing;
 document.querySelector('#length').textContent=Math.round(totalLength);document.querySelector('#corners').textContent=points.length;document.querySelector('#estimate').textContent=Math.round(totalLength/13);document.querySelector('#difficulty').textContent=closed?'Custom circuit':'Draft';}
buildTrack();
const rebuildSurroundings=createSurroundings(scenery);
function updateSurroundings(){rebuildSurroundings({samples,width,siteScale,outerPaths:trackModel?.outerPaths??[],...environment});scenery.visible=showScenery;}
updateSurroundings();
const {kart,wheels:kartWheels,frontPivots}=createKart();scene.add(kart);
let velocity=0,heading=0,steering=0,lapStart=0,laps=0,progress=0,lastProgress=.035,lapArmed=false,bestLap=null;const keys=new Set();
function resetKart(){kart.visible=closed&&points.length>=3;if(!curve)return;const p=curve.getPointAt(.035),t=curve.getTangentAt(.035);kart.position.copy(p);heading=Math.atan2(t.x,t.z);kart.rotation.y=heading;velocity=0;steering=0;frontPivots.forEach(w=>w.rotation.y=0);if(driving){camera.position.set(p.x-Math.sin(heading)*10,6.5,p.z-Math.cos(heading)*10);camera.lookAt(p.x+Math.sin(heading)*6,1.2,p.z+Math.cos(heading)*6);}lapStart=performance.now();lastProgress=.035;progress=0;lapArmed=false;}
resetKart();
const $=s=>document.querySelector(s);function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function setEdit(value){editing=value;handleGroup.visible=value;$('#edit').classList.toggle('selected',value);$('#orbit').classList.toggle('selected',!value);$('#editBanner').classList.toggle('hidden',!value);}
function cameraView(top=false){setView(top?'2d':'3d');}
function setView(mode){if(driving)return;viewMode=mode;overhead=mode!=='3d';controls.enabled=mode==='3d';container.style.visibility=mode==='3d'?'visible':'hidden';$('#viewport').classList.toggle('plan-active',mode!=='3d');$('#viewLabel').textContent=mode==='3d'?'3D perspective':mode==='2d'?'Scale drawing':'Circuit silhouette';$('#viewHint').textContent=mode==='3d'?'Drag to orbit · Scroll to zoom':mode==='2d'?'Click to draw · Scroll to zoom · Space + drag to pan':'Circuit only · Scroll to zoom · Drag to pan';$('#modeLabel').textContent=mode==='2d'?'DESIGN CANVAS':mode==='outline'?'CIRCUIT PLAN':'LIVE PREVIEW';for(const [id,m] of [['#view2d','2d'],['#view3d','3d'],['#viewOutline','outline']])$(id).classList.toggle('selected',mode===m);$('#exportSvg').classList.toggle('hidden',mode!=='outline');$('#geometryLegend').classList.toggle('hidden',!geometryDebug||mode!=='3d');setEdit(false);editor?.setMode(mode);if(mode==='3d'){const center=points.length?points.reduce((a,p)=>[a[0]+p[0]/points.length,a[1]+p[1]/points.length],[0,0]):[0,0];controls.target.set(center[0],0,center[1]);camera.position.set(center[0]+133*siteScale,145*siteScale,center[1]+166*siteScale);updateSurroundings();}else if(mode==='outline')editor?.fit();}
editor=createEditor({host:$('#viewport'),getState:()=>({points,closed,width,samples,siteScale}),onChange:s=>{points=s.points;closed=s.closed;buildTrack();resetKart();},onMode:setView});
$('#edit').onclick=()=>setView('2d');$('#orbit').onclick=()=>setView('3d');$('#top').onclick=()=>setView('2d');$('#view2d').onclick=()=>setView('2d');$('#view3d').onclick=()=>setView('3d');$('#viewOutline').onclick=()=>setView('outline');$('#exportSvg').onclick=()=>editor.export();$('#reset').onclick=()=>{if(viewMode==='3d')setView('3d');else editor.fit();};$('#zoomIn').onclick=()=>{if(viewMode==='3d')camera.position.lerp(controls.target,.15);else editor.zoom(.8);};$('#zoomOut').onclick=()=>{if(viewMode==='3d')camera.position.sub(controls.target).multiplyScalar(1.15).add(controls.target);else editor.zoom(1.25);};
setView('2d');
$('#siteScale').onchange=e=>{const next=Number(e.target.value);if(points.some(p=>!pointInsideSite(p,next))){e.target.value=siteScale;toast('Move outer corners inward before reducing the circuit area.');return;}siteScale=next;updateSite();editor.render();editor.fitSite();if(viewMode==='3d')setView('3d');else updateSurroundings();toast(`${next===1?'Standard':next===2?'Large':'Grand'} circuit area ready.`);};
for(const [id,key] of [['#treesOption','trees'],['#facilitiesOption','facilities'],['#barriersOption','barriers']])$(id).onchange=e=>{environment[key]=e.target.checked;updateSurroundings();};$('#biome').onchange=e=>{environment.biome=e.target.value;updateSurroundings();};
$('#sceneryDensity').oninput=e=>{environment.density=+e.target.value;$('#sceneryDensityValue').textContent=environment.density<80?'Open':environment.density>130?'Lush':'Medium';updateSurroundings();};
$('#width').oninput=e=>{width=+e.target.value;$('#widthValue').textContent=width;buildTrack();editor.render();updateSurroundings();};
$('#smoothness').oninput=e=>{smoothness=+e.target.value;$('#smoothnessValue').textContent=smoothness<.3?'Precise':smoothness>.55?'Flowing':'Balanced';buildTrack();editor.render();updateSurroundings();};
for(const [id,key] of [['curbWidth','curbWidth'],['runoffWidth','runoffWidth'],['miterLimit','miterLimit']])$('#'+id).oninput=e=>{if(key==='curbWidth')curbWidth=+e.target.value;else if(key==='runoffWidth')runoffWidth=+e.target.value;else miterLimit=+e.target.value;$('#'+id+'Value').textContent=Number(e.target.value).toFixed(1).replace(/\.0$/,'');buildTrack();updateSurroundings();};
$('#geometryDebug').onchange=e=>{geometryDebug=e.target.checked;$('#geometryLegend').classList.toggle('hidden',!geometryDebug);buildTrack();if(geometryDebug&&viewMode!=='3d')setView('3d');};
$('#curbs').onclick=()=>{showCurbs=!showCurbs;$('#curbs').classList.toggle('on',showCurbs);$('#curbs').setAttribute('aria-checked',showCurbs);buildTrack();};$('#scenery').onclick=()=>{showScenery=!showScenery;scenery.visible=showScenery;$('#scenery').classList.toggle('on',showScenery);$('#scenery').setAttribute('aria-checked',showScenery);};
document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{const golden=b.dataset.light==='golden';sun.color.set(golden?'#ffc17b':'#fff5dd');sun.position.set(-70,golden?35:110,65);ambient.intensity=golden?1.8:2.5;scene.background.set(golden?'#d6bea0':'#c6ceba');scene.fog.color.copy(scene.background);document.querySelectorAll('[data-light]').forEach(v=>v.classList.toggle('selected',v===b));});
$('#trackName').oninput=e=>{$('#canvasName').textContent=e.target.value.trim()||'Untitled circuit';};
$('#undo').onclick=()=>editor.undo();
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
function driveToggle(){if(!driving){if(!closed||points.length<3)return;setView('3d');}driving=!driving;setEdit(false);controls.enabled=!driving;$('#drive').innerHTML=driving?`${icon('square')} End test drive`:`${icon('flag')} Test drive ${icon('arrow-up-right')}`;$('#modeLabel').textContent=driving?'ON THE CIRCUIT':'LIVE PREVIEW';$('#driveHud').classList.toggle('hidden',!driving);$('#viewHint').innerHTML=driving?'W / ↑ Accelerate <span>·</span> S / ↓ Brake & reverse <span>·</span> A D Steer <span>·</span> R Reset':`${icon('mouse')} Drag to orbit <span>·</span> Scroll to zoom`;$('.canvas-title').classList.toggle('hidden',driving);$('.view-tools').classList.toggle('hidden',driving);$('.view-switch').classList.toggle('hidden',driving);$('#width').disabled=driving;$('.sidebar').inert=driving;keys.clear();if(driving){resetKart();laps=0;$('#lapCount').textContent='LAP 01';toast('You’re in the driver’s seat. Use WASD or arrow keys.');}else cameraView(false);createIcons({icons});}
$('#drive').onclick=driveToggle;$('#respawn').onclick=resetKart;
const touchControls=document.createElement('div');touchControls.className='touch-controls';touchControls.innerHTML='<div><button data-key="a" aria-label="Steer left">←</button><button data-key="d" aria-label="Steer right">→</button></div><div><button data-key="s" aria-label="Brake and reverse">BRAKE</button><button data-key="w" aria-label="Accelerate">GO ↑</button></div>';$('#viewport').append(touchControls);
new MutationObserver(()=>touchControls.classList.toggle('visible',driving)).observe($('#driveHud'),{attributes:true,attributeFilter:['class']});
touchControls.querySelectorAll('button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
window.addEventListener('keydown',e=>{if(e.target.matches('input')||$('#savedDialog').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(driving&&e.key.toLowerCase()==='r')resetKart();if(driving&&e.key==='Escape')driveToggle();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let dragged=null;
function pointerRay(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);}
renderer.domElement.addEventListener('pointerdown',e=>{if(!editing)return;pointerRay(e);const hit=raycaster.intersectObjects(handleGroup.children);if(hit.length){dragged=hit[0].object.userData.index;undoStack.push(points.map(p=>[...p]));controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);}},true);
renderer.domElement.addEventListener('pointermove',e=>{if(dragged===null)return;pointerRay(e);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){points[dragged]=clampToSite([p.x,p.z],siteScale);buildTrack();}});
renderer.domElement.addEventListener('pointerup',()=>{if(dragged!==null){dragged=null;controls.enabled=true;resetKart();}});
$('#save').onclick=()=>{if(!points.length){toast('Place a point before saving your circuit.');return;}const data={id:Date.now(),name:$('#trackName').value.trim()||'Untitled circuit',points:points.map(p=>[...p]),closed,width,smoothness,curbWidth,runoffWidth,miterLimit,siteScale,showCurbs,showScenery,environment:{...environment}};const existing=saved.findIndex(s=>s.name===data.name);if(existing>=0)saved[existing]=data;else saved.push(data);try{localStorage.setItem('apex-circuits',JSON.stringify(saved));$('#saveCount').textContent=saved.length;toast('Circuit saved. Your next lap is waiting.');}catch{toast('Storage is full or unavailable. Unable to save circuit.');}};
function showSaved(open=true){
  const list=$('#savedList');list.replaceChildren();
  if(!saved.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Your garage is empty. Design a circuit and save it to find it here.';list.append(p);}
  saved.forEach(s=>{
    const row=document.createElement('div');row.className='saved-row';
    const load=document.createElement('button');load.className='saved-item';load.type='button';
    const title=document.createElement('strong');title.textContent=s.name;
    const detail=document.createElement('span');detail.textContent=`${s.points.length} corners · ${s.width} m wide · ${s.siteScale===3?'Grand':s.siteScale===2?'Large':'Standard'} area →`;
    load.append(title,detail);
    load.onclick=()=>{if(driving)driveToggle();points=s.points.map(p=>[...p]);width=s.width;siteScale=[1,2,3].includes(Number(s.siteScale))?Number(s.siteScale):1;updateSite();$('#siteScale').value=siteScale;smoothness=s.smoothness??.4;curbWidth=s.curbWidth??.9;runoffWidth=s.runoffWidth??1.1;miterLimit=s.miterLimit??2;closed=s.closed??true;showCurbs=s.showCurbs??true;showScenery=s.showScenery??true;environment={trees:true,facilities:true,barriers:true,biome:'park',density:100,...s.environment};$('#scenery').classList.toggle('on',showScenery);$('#scenery').setAttribute('aria-checked',showScenery);for(const [id,key] of [['#treesOption','trees'],['#facilitiesOption','facilities'],['#barriersOption','barriers']])$(id).checked=environment[key];$('#biome').value=environment.biome;$('#sceneryDensity').value=environment.density;$('#sceneryDensityValue').textContent=environment.density<80?'Open':environment.density>130?'Lush':'Medium';$('#curbs').classList.toggle('on',showCurbs);$('#curbs').setAttribute('aria-checked',showCurbs);$('#trackName').value=s.name;$('#canvasName').textContent=s.name;$('#width').value=width;$('#widthValue').textContent=width;$('#smoothness').value=smoothness;$('#smoothnessValue').textContent=smoothness<.3?'Precise':smoothness>.55?'Flowing':'Balanced';for(const [id,value] of [['curbWidth',curbWidth],['runoffWidth',runoffWidth],['miterLimit',miterLimit]]){$('#'+id).value=value;$('#'+id+'Value').textContent=Number(value).toFixed(1).replace(/\.0$/,'');}undoStack=[];editor.resetHistory();buildTrack();resetKart();updateSurroundings();setView('2d');editor.fit();$('#savedDialog').close();toast('Circuit loaded. Make it yours.');};
    const remove=document.createElement('button');remove.type='button';remove.className='saved-delete';remove.setAttribute('aria-label',`Delete ${s.name}`);remove.title='Delete saved circuit';remove.innerHTML='<i data-lucide="trash-2"></i>';
    remove.onclick=()=>{if(!window.confirm(`Delete "${s.name}" from My circuits?`))return;const next=saved.filter(item=>item!==s);try{localStorage.setItem('apex-circuits',JSON.stringify(next));saved=next;$('#saveCount').textContent=saved.length;showSaved(false);toast('Saved circuit deleted.');}catch{toast('Unable to delete circuit from storage.');}};
    row.append(load,remove);list.append(row);
  });
  createIcons({icons:{Trash2}});
  if(open)$('#savedDialog').showModal();
}
$('#circuitsNav').onclick=showSaved;$('#closeDialog').onclick=()=>$('#savedDialog').close();$('#studioNav').onclick=()=>$('#savedDialog').close();
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);resize();
let previous=performance.now();
function frame(now){
  requestAnimationFrame(frame);
  const dt=Math.min((now-previous)/1000,.045);previous=now;
  if(driving){
    let nearest=Infinity,idx=0;
    for(let i=0;i<samples.length;i++){const d=kart.position.distanceToSquared(samples[i]);if(d<nearest){nearest=d;idx=i;}}
    const onRoad=Math.sqrt(nearest)<width/2;
    const throttle=keys.has('w')||keys.has('arrowup'),brake=keys.has('s')||keys.has('arrowdown');
    const steer=Number(keys.has('a')||keys.has('arrowleft'))-Number(keys.has('d')||keys.has('arrowright'));
    const next=stepKart({x:kart.position.x,z:kart.position.z,heading,speed:velocity,steering},{throttle,brake,steer},dt,onRoad);
    const bounds=siteBounds(siteScale);
    kart.position.x=THREE.MathUtils.clamp(next.x,bounds.minX-17,bounds.maxX+17);
    kart.position.z=THREE.MathUtils.clamp(next.z,bounds.minZ-19,bounds.maxZ+19);
    heading=next.heading;velocity=next.speed;steering=next.steering;kart.rotation.y=heading;
    frontPivots.forEach(w=>w.rotation.y=steering);
    kartWheels.forEach(w=>w.rotation.x+=velocity*dt/.42);
    const t=idx/Math.max(1,samples.length-1);let delta=t-lastProgress;
    if(delta>.5)delta-=1;if(delta<-.5)delta+=1;
    if(onRoad&&Math.abs(delta)<.06)progress+=delta;lastProgress=t;
    if(progress>.85)lapArmed=true;
    if(lapArmed&&progress>=1&&onRoad){const time=(now-lapStart)/1000;bestLap=bestLap?Math.min(time,bestLap):time;laps++;lapStart=now;progress=0;lapArmed=false;$('#lapCount').textContent=`LAP ${String(laps+1).padStart(2,'0')}`;toast(`Lap complete · ${time.toFixed(2)}s — Best ${bestLap.toFixed(2)}s`);}
    const seconds=(now-lapStart)/1000;$('#lapTime').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${(seconds%60).toFixed(2).padStart(5,'0')}`;
    $('#speed').textContent=Math.round(Math.abs(velocity)*3.6);
    const behind=new THREE.Vector3(-Math.sin(heading)*10,6.5,-Math.cos(heading)*10);
    const target=kart.position.clone().add(behind);
    camera.position.lerp(target,1-Math.exp(-4.4*dt));
    camera.lookAt(kart.position.clone().add(new THREE.Vector3(Math.sin(heading)*6,1.2,Math.cos(heading)*6)));
  }else if(viewMode==='3d')controls.update();
  if(driving||viewMode==='3d')renderer.render(scene,camera);
}
requestAnimationFrame(frame);
